apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fraud-detection

resources:
  # Resources for s3 object storage.
  - datascienceproject-fraud-detection.yaml
  - setup-s3.yaml