apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../operator/overlays/stable
  - ../../../instance/knative-serving/overlays/default
  - ../../../instance/knative-eventing/overlays/knative-kafka
