apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Resources for s3 object storage.
  - ../minio
  # Resources for pipeline.
  - ./namespace-arl-work.yaml
  - ./secret-pipelines.yaml
  - ./datasciencepipelinesapplication-dspa.yaml
  - ./rolebindings-arl-work-modelregistry-rolebinding.yaml